---
title: "K-factor Analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Setup 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,tidymodels)
ATP_Data <- read.csv('Final.csv')
ATP_Data <- subset(ATP_Data,score != "W/O")
```

## Changing K

```{r}
#Setting up dataframes to track the result
Change_K_Result <- as_tibble(data.frame(year=c(1992:2021)))
Reduced_ATP_Data<- ATP_Data %>% select(tourney_id,tourney_name,winner_name,loser_name,tourney_level)
count <- 1
# k is the values of k we will check 
for(k in seq(10,200,10)){
  #This sets up a dataframe to track all the players elo values, default to 1500 to start
  players_win <- unique(Reduced_ATP_Data$winner_name)
  players_lose <- unique(Reduced_ATP_Data$loser_name)
  players_total <- c(players_lose,players_win)
  players_total <- unique(players_total)
  players_total<-as_tibble(players_total)
  players_total<-players_total %>% add_column(rep(1500,nrow(players_total))) %>% rename(Names = value, Elo = `rep(1500, nrow(players_total))`)
  Elo_rating_k <- rep(0,30)
  Name_k <- rep(0,30)
  print(k)
for(j in 1992:2021){
  print(j)
  Year_ATP_Data<-Reduced_ATP_Data %>% subset(substr(tourney_id,start = 1,stop = 4)== j )
  l <- nrow(Year_ATP_Data)

  for(i in 1:l){
  #Elo calculation
    Player_A <- players_total$Elo[match(Year_ATP_Data$winner_name[i],players_total$Names)]
    Player_B <- players_total$Elo[match(Year_ATP_Data$loser_name[i],players_total$Names)]
    
    EA <- 1/(1+10^((Player_B-Player_A)/400))
    EB <- 1/(1+10^((Player_A-Player_B)/400))
    
    players_total$Elo[match(Year_ATP_Data$winner_name[i],players_total$Names)] <- Player_A +k*(1-EA)
    players_total$Elo[match(Year_ATP_Data$loser_name[i],players_total$Names)] <- Player_B + k*(-EB)
    if(i/1000==round(i/1000)){
      
    }
    
    
  }
  # Sorts players by Elo high to low
  players_total<- players_total %>% arrange(desc(Elo))
  
  Elo_rating_k[count] <- players_total$Elo[1]
  Name_k[count] <- players_total$Names[1]

  count<-count+1
}
  #Store the top player for each year
  Change_K_Result[ ,ncol(Change_K_Result) + 1 ] <- Name_k
  colnames(Change_K_Result)[ncol(Change_K_Result)] <- paste0("First Name", k)
  count<-1
}
# Slow function so writes the result
write.csv(Change_K_Result,"Changing Kfactor Results.csv")
```

Setting the results for number of unique number 1's in each year for each K value

```{r}
Number_of_people <- as_tibble(data.frame(year=c(1992:2021)))
Year_num <- rep(0,nrow(Change_K_Result))
Name_unique <- rep(NaN,nrow(Change_K_Result))
for(i in 1:nrow(Change_K_Result))
  {
  print(i)
 
  temp<-Change_K_Result %>% slice(i) %>% unlist(., use.names=FALSE)
  temp<- temp[3:length(temp)]
  Year_num[i] <- length(unique(temp))
  if(length(unique(temp))==1){
    Name_unique[i] <- unique(temp)
  }
}
Number_of_people[ ,ncol(Number_of_people) + 1 ] <- Year_num
  colnames(Number_of_people)[ncol(Number_of_people)] <- paste0("Unique people")
  Number_of_people[ ,ncol(Number_of_people) + 1 ] <- Name_unique
  colnames(Number_of_people)[ncol(Number_of_people)] <- paste0("Unique Name ifapp")
  
  write.csv(Number_of_people,"Number of Elo Leaders With Changing K.csv")
```

## Only to 60
Does the same as the funciton above but only store for k 10-60

```{r}
#Number_of_people <- as_tibble(data.frame(year=c(1992:2021)))
Year_num <- rep(0,nrow(Change_K_Result))
Name_unique <- rep(NaN,nrow(Change_K_Result))
for(i in 1:nrow(Change_K_Result))
  {
  print(i)
  
temp<- Change_K_Result %>% slice(i) %>% unlist(., use.names=FALSE)
  temp<-temp[3:6]
  Year_num[i] <- length(unique(temp))
  print(temp)
  if(length(unique(temp))==1){
    Name_unique[i] <- unique(temp)
  }
}
Number_of_people[ ,ncol(Number_of_people) + 1 ] <- Year_num
  colnames(Number_of_people)[ncol(Number_of_people)] <- paste0("Unique people reduced")
  Number_of_people[ ,ncol(Number_of_people) + 1 ] <- Name_unique
  colnames(Number_of_people)[ncol(Number_of_people)] <- paste0("Unique Name ifapp reduced")

```


## Getting data back

reloading all the data if you are using this function more than once 

```{r}
Number_of_Elo_leaders <- read.csv("Number of Elo Leaders With Changing K.csv")
Change_K_Result <- read.csv("Changing Kfactor Results.csv")
Number_of_Elo_leaders <- rename(Unique_people = Unique.people)
Number_of_people[ 4] <- Number_of_people$`Unique people`
```

## Plotting

```{r}
#Number_of_Elo_leaders$Unique.people

ggplot() +
  geom_step(aes(year+.1,`Unique people`+.02,colour = "k range 10-200"),data = Number_of_people) + geom_step(aes(year,`Unique people reduced`,color = "k range 20-60"),data = Number_of_people)+
  scale_y_continuous(breaks = c(0, 1, 2, 3)) +
  scale_x_continuous(breaks = c(seq(1992,2021,2))) +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  ))+xlab("Year")+ylab("Number of unique end of year leaders")+ theme(axis.title.x =
          element_blank()) + theme(
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            legend.title = element_blank(),
            axis.line = element_line(colour = "black"),
            panel.border = element_rect(color = "black", fill = NA, size = 2),
            text = element_text(size=20)
          )
  

```



